# Generated by Django 3.2 on 2021-04-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210409_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimg',
            name='image',
            field=models.ImageField(null=True, upload_to='static/image/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='uploadvideo',
            name='video',
            field=models.FileField(null=True, upload_to='static/video/', verbose_name='video'),
        ),
    ]
