# Generated by Django 3.2 on 2021-04-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210409_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImgMenu2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='static/image/', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='UploadImgMenu3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='static/image/', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='UploadImgMenu4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='static/image/', verbose_name='image')),
            ],
        ),
        migrations.RenameModel(
            old_name='UploadImg',
            new_name='UploadImgMenu1',
        ),
    ]
