# Generated by Django 3.2 on 2021-04-30 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
