# Generated by Django 3.2 on 2021-04-30 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImgMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_no', models.IntegerField(verbose_name='menu_number')),
                ('image', models.ImageField(null=True, upload_to='static/image/', verbose_name='image')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadimgmenu2',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='uploadimgmenu3',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='uploadimgmenu4',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='UploadImgMenu1',
        ),
        migrations.DeleteModel(
            name='UploadImgMenu2',
        ),
        migrations.DeleteModel(
            name='UploadImgMenu3',
        ),
        migrations.DeleteModel(
            name='UploadImgMenu4',
        ),
    ]
