# Generated by Django 3.2 on 2021-04-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210430_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimgmenu',
            name='menu_no',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='menu_number'),
        ),
    ]
